### ISSUE TITLE
Windows Explorer context menu "Open with hyperdbg"

### ISSUE THREAD

**Issue by ddkwork** [HyperDbg/gui#141]

**Comment by ddkwork** [comment]
https://github.com/HyperDbg/gui/blob/main/open.reg

The unit test fails, it seems that the location is not referenced correctly

**Comment by SinaKarvandi** [comment]
One important note to consider. Right now, HyperDbg won't make any changes in the system directories or registry and it's because HyperDbg is a debugger aimed to debug malware or software with lots of anti-debugging methods. Modifying the registry is okay, but then as an anti-debugging method, the target program might look at these registry keys and detect that HyperDbg is running and terminate itself.

I don't mean that this feature is not good. It's of course needed and good. I mean make sure to not modify the registry by default. For example, make an option for the user to choose whether they want to have such a feature as 'open with HyperDbg' or not. This way, those anti-debugging methods cannot rely on these methods to detect HyperDbg. 👌

需要考虑的一个重要事项是，目前 HyperDbg 不会对系统目录或注册表进行任何更改，这是因为 HyperDbg 是一个旨在调试恶意软件或软件的调试器，具有许多反调试方法。修改注册表是可以的，但作为一种反调试方法，目标程序可能会查看这些注册表项并检测到 HyperDbg 正在运行并终止自身。

我并不是说这个功能不好。它当然是需要的，而且很好。我的意思是确保默认情况下不修改注册表。例如，为用户提供一个选项，让他们选择是否要使用“使用 HyperDbg 打开”这样的功能。这样，那些反调试方法就不能依赖这些方法来检测 HyperDbg。👌

**Comment by SinaKarvandi** [comment]
As for the problem. Why unit test is needed for this? I mean it's a Windows registry, why does it need to be tested in the unit test? 

至于问题。为什么需要单元测试？我的意思是它是一个 Windows 注册表，为什么需要在单元测试中进行测试？

**Comment by ddkwork** [comment]
> One important note to consider. Right now, HyperDbg won't make any changes in the system directories or registry and it's because HyperDbg is a debugger aimed to debug malware or software with lots of anti-debugging methods. Modifying the registry is okay, but then as an anti-debugging method, the target program might look at these registry keys and detect that HyperDbg is running and terminate itself.
> 
> I don't mean that this feature is not good. It's of course needed and good. I mean make sure to not modify the registry by default. For example, make an option for the user to choose whether they want to have such a feature as 'open with HyperDbg' or not. This way, those anti-debugging methods cannot rely on these methods to detect HyperDbg. 👌
> 
> 需要考虑的一个重要事项是，目前 HyperDbg 不会对系统目录或注册表进行任何更改，这是因为 HyperDbg 是一个旨在调试恶意软件或软件的调试器，具有许多反调试方法。修改注册表是可以的，但作为一种反调试方法，目标程序可能会查看这些注册表项并检测到 HyperDbg 正在运行并终止自身。
> 
> 我并不是说这个功能不好。它当然是需要的，而且很好。我的意思是确保默认情况下不修改注册表。例如，为用户提供一个选项，让他们选择是否要使用“使用 HyperDbg 打开”这样的功能。这样，那些反调试方法就不能依赖这些方法来检测 HyperDbg。👌

Your suggestion is very informative, I'll provide a setting option to let users choose whether to register shortcuts or not

**Comment by SinaKarvandi** [comment]
Thanks

**Comment by ddkwork** [comment]
> As for the problem. Why unit test is needed for this? I mean it's a Windows registry, why does it need to be tested in the unit test? 
> 
> 至于问题。为什么需要单元测试？我的意思是它是一个 Windows 注册表，为什么需要在单元测试中进行测试？

My description is not precise enough, what I want to express is that an exception occurs after importing the reg and it does not pass the test

**Comment by SinaKarvandi** [comment]
Does it work locally on Windows? Could we ignore the registry in the unit tests?

它能在 Windows 本地运行吗？我们可以在单元测试中忽略注册表吗？

**Comment by ddkwork** [comment]
> Does it work locally on Windows? Could we ignore the registry in the unit tests?
> 
> 它能在 Windows 本地运行吗？我们可以在单元测试中忽略注册表吗？

sure, wait me commit later

**Comment by ddkwork** [comment]
![26262417-c546-469d-9e19-1413cf262980.png](https://github.com/HyperDbg/gui/assets/19886504/f012f306-da44-4a6a-b1f4-552cad1af482)

There are some bugs in the layout of the setup interface that I'll fix later, and then we'll test the reg file response bugs again!

**Comment by ddkwork** [comment]
The explorer right click doesn't take effect immediately after the reg is adjusted to the menu, I thought about restarting explorer to refresh it, but that's not the best way to do it. Do you have any suggestions?

**Comment by ddkwork** [comment]
![screenshots](https://github.com/HyperDbg/gui/assets/19886504/d5052de2-1fe6-4192-8357-c7d022edca41)
Pull the latest commit compilation

**Comment by SinaKarvandi** [comment]
Let me check it.

**Comment by SinaKarvandi** [comment]
It even won't show the 'Open with HyperDbg' for me : (email)🤔
它甚至不会向我显示‘使用 HyperDbg 打开’：（电子邮件）🤔

![image](https://github.com/HyperDbg/gui/assets/13383992/f997ffc1-1534-4ec1-bf9f-dc394f8e75e9)

**Comment by ddkwork** [comment]
Check to see if open.reg has been generated in the run directory.



---Original---
From: "Sina ***@***.***&gt;
Date: Wed, Jul 10, 2024 18:20 PM
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;"State ***@***.***&gt;;
Subject: Re: [HyperDbg/gui] Windows Explorer context menu "Open with hyperdbg"(Issue #141)




 
It even won't show the 'Open with HyperDbg' for me : (email)🤔
 它甚至不会向我显示‘使用 HyperDbg 打开’：（电子邮件）🤔
 
image.png (view on web)

**Comment by SinaKarvandi** [comment]
Yes, it is. But still won't work. If I find a solution I'll let you know. (email (image))
是的，但还是不行。如果我找到解决办法，我会告诉你的。（电子邮件（图片））

![image](https://github.com/HyperDbg/gui/assets/13383992/61976a4b-c8e8-4f00-bee9-f55b4d5cdb90)

**Comment by SinaKarvandi** [comment]
```
Sina@DESKTOP-1PRT1T8 MINGW64 ~/Desktop/gui (main)
$ go run .
2024-07-10 03:16:19    Trace ->  --------- title --------- │ ------------------ info ------------------ //runtime.doInit1+0xec C:/Program Files/Go/src/runtime/proc.go:7176
2024-07-10 03:16:19    Trace ->                    sysPath │ C:\Users\Sina\AppData\Local\hyperdbg\cache\NEt6VJENyeruE_sWSSvv5v4LAmon0Rl0tRhE8mEV4Ms\hyperkd.sys //github.com/ddkwork/HyperDbg/sdk.init.0+0x1fa C:/Users/Sina/Desktop/gui/sdk/init.go:29
2024-07-10 03:16:19    Error ->                            │ CreateFile C:/Users/Sina/AppData/Local/hyperdbg/cache/NEt6VJENyeruE_sWSSvv5v4LAmon0Rl0tRhE8mEV4Ms: The system cannot find the path specified.
                                                           │ github.com/ddkwork/HyperDbg/sdk.init.0+0x278 C:/Users/Sina/Desktop/gui/sdk/init.go:31

2024-07-10 03:16:19  Warning ->                            │ 如果第一次看到这个错误，则说明当前目录下没有这个目录，请手动检查目录结构，如果第二次运行还出现权限错误则需要检查代码和系统问题 //github.com/ddkwork/golibrary/stream.CreatDirectory+0xb7 C:/Users/Sina/go/pkg/mod/github.com/ddkwork/golibrary@v0.0.0-20240709142820-a5c7470d21ac/stream/safeStream.go:198
2024-07-10 03:16:20     Info ->                            │ virtualization technology is vt-x //github.com/ddkwork/HyperDbg/sdk.VmxSupportDetection+0x108 C:/Users/Sina/Desktop/gui/sdk/util.go:45
2024-07-10 03:16:20     Info ->                            │ vmx operation is supported by your processor //github.com/ddkwork/HyperDbg/sdk.VmxSupportDetection+0x16a C:/Users/Sina/Desktop/gui/sdk/util.go:51
OEP File Off 1fde0
OEP VA 1400209e0
Entry Point RVA 209e0
OEP Data 488954241048894c24084881ec88000000c74424400000000048c74424500000000048c744245800000000b83c0000006689442460b83e0000006689442462488d05da4900004889442468b8440000006689442470b8460000006689442472488d05fa49
2024-07-10 03:16:34    Error ->                            │ 不支持的文件类型
                                                           │ github.com/ddkwork/app/widget.(*Field).SetText+0x44 C:/Users/Sina/go/pkg/mod/github.com/ddkwork/app@v0.0.0-20240710052909-09841d49bbe5/widget/field.go:1030
                                                           │ github.com/ddkwork/app/widget.NewCodeEditor+0x21a C:/Users/Sina/go/pkg/mod/github.com/ddkwork/app@v0.0.0-20240710052909-09841d49bbe5/widget/CodeEditor.go:46
                                                           │ github.com/ddkwork/HyperDbg/ux.LayoutCpu+0x10e C:/Users/Sina/Desktop/gui/ux/cpu.go:167
                                                           │ github.com/ddkwork/HyperDbg/ux.NewTabPage+0xb5 C:/Users/Sina/Desktop/gui/ux/ux.go:120
                                                           │ github.com/ddkwork/app.run.func1.1+0x133 C:/Users/Sina/go/pkg/mod/github.com/ddkwork/app@v0.0.0-20240710052909-09841d49bbe5/app.go:54
                                                           │ github.com/richardwilkes/toolbox.CallWithHandler+0x47 C:/Users/Sina/go/pkg/mod/github.com/richardwilkes/toolbox@v1.114.1/call.go:24
                                                           │ github.com/richardwilkes/toolbox.Call+0x6a C:/Users/Sina/go/pkg/mod/github.com/richardwilkes/toolbox@v1.114.1/call.go:18
                                                           │ github.com/richardwilkes/unison.finishStartup+0x5e C:/Users/Sina/go/pkg/mod/github.com/richardwilkes/unison@v0.71.0/app.go:183
                                                           │ github.com/richardwilkes/toolbox.CallWithHandler+0x47 C:/Users/Sina/go/pkg/mod/github.com/richardwilkes/toolbox@v1.114.1/call.go:24
                                                           │ github.com/richardwilkes/unison.processNextTask+0x12d C:/Users/Sina/go/pkg/mod/github.com/richardwilkes/unison@v0.71.0/task.go:51
                                                           │ github.com/richardwilkes/unison.processEvents+0x2a C:/Users/Sina/go/pkg/mod/github.com/richardwilkes/unison@v0.71.0/app.go:164
                                                           │ github.com/richardwilkes/unison.Start+0x156 C:/Users/Sina/go/pkg/mod/github.com/richardwilkes/unison@v0.71.0/app.go:158
                                                           │ github.com/ddkwork/app.run+0x18 C:/Users/Sina/go/pkg/mod/github.com/ddkwork/app@v0.0.0-20240710052909-09841d49bbe5/app.go:45
                                                           │ github.com/ddkwork/app.RunWithIco+0x55 C:/Users/Sina/go/pkg/mod/github.com/ddkwork/app@v0.0.0-20240710052909-09841d49bbe5/app.go:41
                                                           │ github.com/ddkwork/HyperDbg/ux.Run+0x17 C:/Users/Sina/Desktop/gui/ux/ux.go:38
                                                           │ main.main+0xe C:/Users/Sina/Desktop/gui/main.go:11

2024-07-10 03:16:35    Error ->                            │ 不支持的文件类型
                                                           │ github.com/ddkwork/app/widget.(*Field).SetText+0x44 C:/Users/Sina/go/pkg/mod/github.com/ddkwork/app@v0.0.0-20240710052909-09841d49bbe5/widget/field.go:1030
                                                           │ github.com/ddkwork/HyperDbg/ux.LayoutCpu+0x159 C:/Users/Sina/Desktop/gui/ux/cpu.go:168
                                                           │ github.com/ddkwork/HyperDbg/ux.NewTabPage+0xb5 C:/Users/Sina/Desktop/gui/ux/ux.go:120
                                                           │ github.com/ddkwork/app.run.func1.1+0x133 C:/Users/Sina/go/pkg/mod/github.com/ddkwork/app@v0.0.0-20240710052909-09841d49bbe5/app.go:54
                                                           │ github.com/richardwilkes/toolbox.CallWithHandler+0x47 C:/Users/Sina/go/pkg/mod/github.com/richardwilkes/toolbox@v1.114.1/call.go:24
                                                           │ github.com/richardwilkes/toolbox.Call+0x6a C:/Users/Sina/go/pkg/mod/github.com/richardwilkes/toolbox@v1.114.1/call.go:18
                                                           │ github.com/richardwilkes/unison.finishStartup+0x5e C:/Users/Sina/go/pkg/mod/github.com/richardwilkes/unison@v0.71.0/app.go:183
                                                           │ github.com/richardwilkes/toolbox.CallWithHandler+0x47 C:/Users/Sina/go/pkg/mod/github.com/richardwilkes/toolbox@v1.114.1/call.go:24
                                                           │ github.com/richardwilkes/unison.processNextTask+0x12d C:/Users/Sina/go/pkg/mod/github.com/richardwilkes/unison@v0.71.0/task.go:51
                                                           │ github.com/richardwilkes/unison.processEvents+0x2a C:/Users/Sina/go/pkg/mod/github.com/richardwilkes/unison@v0.71.0/app.go:164
                                                           │ github.com/richardwilkes/unison.Start+0x156 C:/Users/Sina/go/pkg/mod/github.com/richardwilkes/unison@v0.71.0/app.go:158
                                                           │ github.com/ddkwork/app.run+0x18 C:/Users/Sina/go/pkg/mod/github.com/ddkwork/app@v0.0.0-20240710052909-09841d49bbe5/app.go:45
                                                           │ github.com/ddkwork/app.RunWithIco+0x55 C:/Users/Sina/go/pkg/mod/github.com/ddkwork/app@v0.0.0-20240710052909-09841d49bbe5/app.go:41
                                                           │ github.com/ddkwork/HyperDbg/ux.Run+0x17 C:/Users/Sina/Desktop/gui/ux/ux.go:38
                                                           │ main.main+0xe C:/Users/Sina/Desktop/gui/main.go:11

2024-07-10 03:16:37  Warning ->                       TODO │ set tab ico //github.com/ddkwork/HyperDbg/ux.(*TagPage).Layout+0x256 C:/Users/Sina/Desktop/gui/ux/ux.go:95
2024-07-10 03:17:07   Struct ->                            │  //github.com/ddkwork/HyperDbg/ux.LayoutDisassemblyTable.func4+0x3c C:/Users/Sina/Desktop/gui/ux/cpu.go:1182
{
 "Address": 5368842800,
 "Opcode": "ZolEJHA=",
 "Instruction": "mov word ptr [rsp+0x70], ax",
 "Comment": ""
}
2024-07-10 03:17:07   Struct ->                            │  //github.com/ddkwork/HyperDbg/ux.LayoutDisassemblyTable.func4+0x3c C:/Users/Sina/Desktop/gui/ux/cpu.go:1182
{
 "Address": 5368842800,
 "Opcode": "ZolEJHA=",
 "Instruction": "mov word ptr [rsp+0x70], ax",
 "Comment": ""
}
2024-07-10 03:17:08   Struct ->                            │  //github.com/ddkwork/HyperDbg/ux.LayoutDisassemblyTable.func4+0x3c C:/Users/Sina/Desktop/gui/ux/cpu.go:1182
{
 "Address": 5368842790,
 "Opcode": "SIlEJGg=",
 "Instruction": "mov qword ptr [rsp+0x68], rax",
 "Comment": ""
}
2024-07-10 03:17:18  Warning ->                 go-command │ C:\Windows\system32\cmd.exe /C reg import open.reg //github.com/ddkwork/golibrary/stream.(*CommandSession).run+0x160 C:/Users/Sina/go/pkg/mod/github.com/ddkwork/golibrary@v0.0.0-20240709142820-a5c7470d21ac/stream/command.go:52
ERROR: Error accessing the registry.
2024-07-10 03:17:18  Warning ->                       line │ ERROR: Error accessing the registry. //github.com/ddkwork/golibrary/stream.(*CommandSession).run.func6+0x4f C:/Users/Sina/go/pkg/mod/github.com/ddkwork/golibrary@v0.0.0-20240709142820-a5c7470d21ac/stream/command.go:113
2024-07-10 03:17:50  Warning ->                 go-command │ C:\Windows\system32\cmd.exe /C reg import open.reg //github.com/ddkwork/golibrary/stream.(*CommandSession).run+0x160 C:/Users/Sina/go/pkg/mod/github.com/ddkwork/golibrary@v0.0.0-20240709142820-a5c7470d21ac/stream/command.go:52
ERROR: Error accessing the registry.
2024-07-10 03:17:50  Warning ->                       line │ ERROR: Error accessing the registry. //github.com/ddkwork/golibrary/stream.(*CommandSession).run.func6+0x4f C:/Users/Sina/go/pkg/mod/github.com/ddkwork/golibrary@v0.0.0-20240709142820-a5c7470d21ac/stream/command.go:113
2024-07-10 03:17:55  Warning ->                 go-command │ C:\Windows\system32\cmd.exe /C reg import open.reg //github.com/ddkwork/golibrary/stream.(*CommandSession).run+0x160 C:/Users/Sina/go/pkg/mod/github.com/ddkwork/golibrary@v0.0.0-20240709142820-a5c7470d21ac/stream/command.go:52
The operation completed successfully.
 //github.com/ddkwork/golibrary/stream.(*CommandSession).run.func6+0x4f C:/Users/Sina/go/pkg/mod/github.com/ddkwork/golibrary@v0.0.0-20240709142820-a5c7470d21ac/stream/command.go:113
2024-07-10 03:17:57  Warning ->                 go-command │ C:\Windows\system32\cmd.exe /C reg import open.reg //github.com/ddkwork/golibrary/stream.(*CommandSession).run+0x160 C:/Users/Sina/go/pkg/mod/github.com/ddkwork/golibrary@v0.0.0-20240709142820-a5c7470d21ac/stream/command.go:52
ERROR: Error accessing the registry.
2024-07-10 03:17:57  Warning ->                       line │ ERROR: Error accessing the registry. //github.com/ddkwork/golibrary/stream.(*CommandSession).run.func6+0x4f C:/Users/Sina/go/pkg/mod/github.com/ddkwork/golibrary@v0.0.0-20240709142820-a5c7470d21ac/stream/command.go:113


```

**Comment by ddkwork** [comment]
Yes I guessed right:Access to the registry is denied. I'm logged in as an administrator account, so a non-administrator account requires the user to double-click the reg file themselves?If that's the case, then the reg file should always be kept visible, I was trying to put it in the temp directory before, but now it seems it should stay as it is!



---Original---
From: "Sina ***@***.***&gt;
Date: Wed, Jul 10, 2024 18:54 PM
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;"State ***@***.***&gt;;
Subject: Re: [HyperDbg/gui] Windows Explorer context menu "Open with hyperdbg"(Issue #141)




 ***@***.*** MINGW64 ~/Desktop/gui (main) $ go run . 2024-07-10 03:16:19    Trace -&gt;  --------- title --------- │ ------------------ info ------------------ //runtime.doInit1+0xec C:/Program Files/Go/src/runtime/proc.go:7176 2024-07-10 03:16:19    Trace -&gt;                    sysPath │ C:\Users\Sina\AppData\Local\hyperdbg\cache\NEt6VJENyeruE_sWSSvv5v4LAmon0Rl0tRhE8mEV4Ms\hyperkd.sys //github.com/ddkwork/HyperDbg/sdk.init.0+0x1fa C:/Users/Sina/Desktop/gui/sdk/init.go:29 2024-07-10 03:16:19    Error -&gt;                            │ CreateFile C:/Users/Sina/AppData/Local/hyperdbg/cache/NEt6VJENyeruE_sWSSvv5v4LAmon0Rl0tRhE8mEV4Ms: The system cannot find the path specified.                                                            │ github.com/ddkwork/HyperDbg/sdk.init.0+0x278 C:/Users/Sina/Desktop/gui/sdk/init.go:31 2024-07-10 03:16:19  Warning -&gt;                            │ 如果第一次看到这个错误，则说明当前目录下没有这个目录，请手动检查目录结构，如果第二次运行还出现权限错误则需要检查代码和系统问题 //github.com/ddkwork/golibrary/stream.CreatDirectory+0xb7 ***@***.***/stream/safeStream.go:198 2024-07-10 03:16:20     Info -&gt;                            │ virtualization technology is vt-x //github.com/ddkwork/HyperDbg/sdk.VmxSupportDetection+0x108 C:/Users/Sina/Desktop/gui/sdk/util.go:45 2024-07-10 03:16:20     Info -&gt;                            │ vmx operation is supported by your processor //github.com/ddkwork/HyperDbg/sdk.VmxSupportDetection+0x16a C:/Users/Sina/Desktop/gui/sdk/util.go:51 OEP File Off 1fde0 OEP VA 1400209e0 Entry Point RVA 209e0 OEP Data 488954241048894c24084881ec88000000c74424400000000048c74424500000000048c744245800000000b83c0000006689442460b83e0000006689442462488d05da4900004889442468b8440000006689442470b8460000006689442472488d05fa49 2024-07-10 03:16:34    Error -&gt;                            │ 不支持的文件类型                                                            │ github.com/ddkwork/app/widget.(*Field).SetText+0x44 ***@***.***/widget/field.go:1030                                                            │ github.com/ddkwork/app/widget.NewCodeEditor+0x21a ***@***.***/widget/CodeEditor.go:46                                                            │ github.com/ddkwork/HyperDbg/ux.LayoutCpu+0x10e C:/Users/Sina/Desktop/gui/ux/cpu.go:167                                                            │ github.com/ddkwork/HyperDbg/ux.NewTabPage+0xb5 C:/Users/Sina/Desktop/gui/ux/ux.go:120                                                            │ github.com/ddkwork/app.run.func1.1+0x133 ***@***.***/app.go:54                                                            │ github.com/richardwilkes/toolbox.CallWithHandler+0x47 ***@***.***/call.go:24                                                            │ github.com/richardwilkes/toolbox.Call+0x6a ***@***.***/call.go:18                                                            │ github.com/richardwilkes/unison.finishStartup+0x5e ***@***.***/app.go:183                                                            │ github.com/richardwilkes/toolbox.CallWithHandler+0x47 ***@***.***/call.go:24                                                            │ github.com/richardwilkes/unison.processNextTask+0x12d ***@***.***/task.go:51                                                            │ github.com/richardwilkes/unison.processEvents+0x2a ***@***.***/app.go:164                                                            │ github.com/richardwilkes/unison.Start+0x156 ***@***.***/app.go:158                                                            │ github.com/ddkwork/app.run+0x18 ***@***.***/app.go:45                                                            │ github.com/ddkwork/app.RunWithIco+0x55 ***@***.***/app.go:41                                                            │ github.com/ddkwork/HyperDbg/ux.Run+0x17 C:/Users/Sina/Desktop/gui/ux/ux.go:38                                                            │ main.main+0xe C:/Users/Sina/Desktop/gui/main.go:11 2024-07-10 03:16:35    Error -&gt;                            │ 不支持的文件类型                                                            │ github.com/ddkwork/app/widget.(*Field).SetText+0x44 ***@***.***/widget/field.go:1030                                                            │ github.com/ddkwork/HyperDbg/ux.LayoutCpu+0x159 C:/Users/Sina/Desktop/gui/ux/cpu.go:168                                                            │ github.com/ddkwork/HyperDbg/ux.NewTabPage+0xb5 C:/Users/Sina/Desktop/gui/ux/ux.go:120                                                            │ github.com/ddkwork/app.run.func1.1+0x133 ***@***.***/app.go:54                                                            │ github.com/richardwilkes/toolbox.CallWithHandler+0x47 ***@***.***/call.go:24                                                            │ github.com/richardwilkes/toolbox.Call+0x6a ***@***.***/call.go:18                                                            │ github.com/richardwilkes/unison.finishStartup+0x5e ***@***.***/app.go:183                                                            │ github.com/richardwilkes/toolbox.CallWithHandler+0x47 ***@***.***/call.go:24                                                            │ github.com/richardwilkes/unison.processNextTask+0x12d ***@***.***/task.go:51                                                            │ github.com/richardwilkes/unison.processEvents+0x2a ***@***.***/app.go:164                                                            │ github.com/richardwilkes/unison.Start+0x156 ***@***.***/app.go:158                                                            │ github.com/ddkwork/app.run+0x18 ***@***.***/app.go:45                                                            │ github.com/ddkwork/app.RunWithIco+0x55 ***@***.***/app.go:41                                                            │ github.com/ddkwork/HyperDbg/ux.Run+0x17 C:/Users/Sina/Desktop/gui/ux/ux.go:38                                                            │ main.main+0xe C:/Users/Sina/Desktop/gui/main.go:11 2024-07-10 03:16:37  Warning -&gt;                       TODO │ set tab ico //github.com/ddkwork/HyperDbg/ux.(*TagPage).Layout+0x256 C:/Users/Sina/Desktop/gui/ux/ux.go:95 2024-07-10 03:17:07   Struct -&gt;                            │  //github.com/ddkwork/HyperDbg/ux.LayoutDisassemblyTable.func4+0x3c C:/Users/Sina/Desktop/gui/ux/cpu.go:1182 {  "Address": 5368842800,  "Opcode": "ZolEJHA=",  "Instruction": "mov word ptr [rsp+0x70], ax",  "Comment": "" } 2024-07-10 03:17:07   Struct -&gt;                            │  //github.com/ddkwork/HyperDbg/ux.LayoutDisassemblyTable.func4+0x3c C:/Users/Sina/Desktop/gui/ux/cpu.go:1182 {  "Address": 5368842800,  "Opcode": "ZolEJHA=",  "Instruction": "mov word ptr [rsp+0x70], ax",  "Comment": "" } 2024-07-10 03:17:08   Struct -&gt;                            │  //github.com/ddkwork/HyperDbg/ux.LayoutDisassemblyTable.func4+0x3c C:/Users/Sina/Desktop/gui/ux/cpu.go:1182 {  "Address": 5368842790,  "Opcode": "SIlEJGg=",  "Instruction": "mov qword ptr [rsp+0x68], rax",  "Comment": "" } 2024-07-10 03:17:18  Warning -&gt;                 go-command │ C:\Windows\system32\cmd.exe /C reg import open.reg //github.com/ddkwork/golibrary/stream.(*CommandSession).run+0x160 ***@***.***/stream/command.go:52 ERROR: Error accessing the registry. 2024-07-10 03:17:18  Warning -&gt;                       line │ ERROR: Error accessing the registry. //github.com/ddkwork/golibrary/stream.(*CommandSession).run.func6+0x4f ***@***.***/stream/command.go:113 2024-07-10 03:17:50  Warning -&gt;                 go-command │ C:\Windows\system32\cmd.exe /C reg import open.reg //github.com/ddkwork/golibrary/stream.(*CommandSession).run+0x160 ***@***.***/stream/command.go:52 ERROR: Error accessing the registry. 2024-07-10 03:17:50  Warning -&gt;                       line │ ERROR: Error accessing the registry. //github.com/ddkwork/golibrary/stream.(*CommandSession).run.func6+0x4f ***@***.***/stream/command.go:113 2024-07-10 03:17:55  Warning -&gt;                 go-command │ C:\Windows\system32\cmd.exe /C reg import open.reg //github.com/ddkwork/golibrary/stream.(*CommandSession).run+0x160 ***@***.***/stream/command.go:52 The operation completed successfully.  //github.com/ddkwork/golibrary/stream.(*CommandSession).run.func6+0x4f ***@***.***/stream/command.go:113 2024-07-10 03:17:57  Warning -&gt;                 go-command │ C:\Windows\system32\cmd.exe /C reg import open.reg //github.com/ddkwork/golibrary/stream.(*CommandSession).run+0x160 ***@***.***/stream/command.go:52 ERROR: Error accessing the registry. 2024-07-10 03:17:57  Warning -&gt;                       line │ ERROR: Error accessing the registry. //github.com/ddkwork/golibrary/stream.(*CommandSession).run.func6+0x4f ***@***.***/stream/command.go:113

**Comment by ddkwork** [comment]
```go
2024-07-10 03:17:18  Warning ->                 go-command │ C:\Windows\system32\cmd.exe /C reg import open.reg  
ERROR: Error accessing the registry.
```

how to fix this ?

**Comment by ddkwork** [comment]
![7adf0d14c46100909e08624aefe6b2a9.png](https://github.com/HyperDbg/gui/assets/19886504/7d95cf99-009c-4834-9adf-f424a56c9496)

**Comment by SinaKarvandi** [comment]
We can use a PowerShell or VBScript to run this command (batch) as administrator:

`powershell -Command "Start-Process cmd -ArgumentList '/c C:\Scripts\MyScript.bat' -Verb RunAs"`

**Comment by SinaKarvandi** [comment]
I think the user should install and load the driver. It's better not to load it automatically without the user's permission.

我认为应该由用户安装并加载驱动程序。最好不要在未经用户许可的情况下自动加载。

**Comment by ddkwork** [comment]
okay



---Original---
From: "Sina ***@***.***&gt;
Date: Wed, Jul 10, 2024 19:12 PM
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;"State ***@***.***&gt;;
Subject: Re: [HyperDbg/gui] Windows Explorer context menu "Open with hyperdbg"(Issue #141)




 
I think the user should install and load the driver. It's better not to load it automatically without the user's permission.
 
我认为应该由用户安装并加载驱动程序。最好不要在未经用户许可的情况下自动加载。

**Comment by ddkwork** [comment]
I will try thanks. And the menu click working for you or not?



---Original---
From: "Sina ***@***.***&gt;
Date: Wed, Jul 10, 2024 19:11 PM
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;"State ***@***.***&gt;;
Subject: Re: [HyperDbg/gui] Windows Explorer context menu "Open with hyperdbg"(Issue #141)




 
We can use a PowerShell or VBScript to run this command (batch) as administrator:
 
powershell -Command "Start-Process cmd -ArgumentList '/c C:\Scripts\MyScript.bat' -Verb RunAs"

**Comment by SinaKarvandi** [comment]
You mean click on the 'Open with HyperDbg'?

**Comment by ddkwork** [comment]
Yes



---Original---
From: "Sina ***@***.***&gt;
Date: Wed, Jul 10, 2024 19:22 PM
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;"State ***@***.***&gt;;
Subject: Re: [HyperDbg/gui] Windows Explorer context menu "Open with hyperdbg"(Issue #141)




 
You mean click on the 'Open with HyperDbg'?

**Comment by SinaKarvandi** [comment]
Nope, the same error as you showed in the GIF, but I couldn't understand what was the reason. Still, investigating.

**Comment by ddkwork** [comment]
Ok, got it



---Original---
From: "Sina ***@***.***&gt;
Date: Wed, Jul 10, 2024 19:24 PM
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;"State ***@***.***&gt;;
Subject: Re: [HyperDbg/gui] Windows Explorer context menu "Open with hyperdbg"(Issue #141)




 
Nope, the same error as you showed in the GIF, but I couldn't understand what was the reason. Still, investigating.
