### ISSUE TITLE
Need c api 

### ISSUE THREAD

**Issue by ddkwork** [HyperDbg/gui#16]
Hello you, i need c++ api bind c api, like this:

https://github.com/richardwilkes/cskia

Then i can use c api call dll or lib file for gui.

**Comment by SinaKarvandi** [comment]
Hi,

I'm not sure if I know exactly what you mean.

Please tell me the specific APIs you want, so I can provide them (if they do not already exist).

Currently, we have the following C APIs available here: 
https://github.com/HyperDbg/HyperDbg/tree/master/hyperdbg/include/SDK/Imports

Do you mean sth other than these APIs? Would you please provide me an example of the kind of API you need?

Thanks

**Comment by ddkwork** [comment]
> Hi,\n\nI'm not sure if I know exactly what you mean.\n\nPlease tell me the specific APIs you want, so I can provide them (if they do not already exist).\n\nCurrently, we have the following C APIs available here:\nhttps://github.com/HyperDbg/HyperDbg/tree/master/hyperdbg/include/SDK/Imports\n\nDo you mean sth other than these APIs? Would you please provide me an example of the kind of API you need?\n\nThanks


like this:

__declspec(dllimport) void HyperDbgScriptReadFileAndExecuteCommand(std::vector<std::string> & PathAndArgs); 
 __declspec(dllimport) bool HyperDbgContinuePreviousCommand(); 
 __declspec(dllimport) bool HyperDbgCheckMultilineCommand(std::string & CurrentCommand, bool Reset);

I don't known what i should set input arg type std:vector , std::string as golang type string or []byte, *byte , unitptr, uint64 ?

**Comment by ddkwork** [comment]
If the arg type is char*, i can use byte* bind it.

**Comment by SinaKarvandi** [comment]
That's okay, I'll convert it to the `char*` now.

**Comment by ddkwork** [comment]
as this: 

Read script file:
Go os.readfile called string arg and convert it to byte* to unsafe.pointer, last call the .h file char* type in to dll function.

Send conmmand is same this.

**Comment by SinaKarvandi** [comment]
what is the "Send conmmand is same this." ? 

Would you please provide its prototype? or a list of functions that need to be converted? 
```
__declspec(dllimport) bool HyperDbgCheckMultilineCommand(std::string & CurrentCommand, bool Reset);
__declspec(dllimport) void HyperDbgScriptReadFileAndExecuteCommand(std::vectorstd::string & PathAndArgs);
```

Is there anything else ?

Currently, I'm working on the following functions:

**Comment by SinaKarvandi** [comment]
Okay, the function you mentioned are now converted to C types : 

https://github.com/HyperDbg/HyperDbg/commit/1b9ba13d5d13aa84faeba9b9f2e39cdc3aff9258

**Comment by SinaKarvandi** [comment]
Please let me know if anything else needs to be changed.

**Comment by ddkwork** [comment]
Sorry my bad english.

Send command means :

Use HyperDbgCheckMultilineCommand
Method when we clicked the gui toolbar's button, like  steup in out etc.

And then the script command " f7 f8,f9" and so on will call HyperDbgCheckMultilineCommand method into driver.

**Comment by ddkwork** [comment]
> what is the "Send conmmand is same this." ? 
> 
> Would you please provide its prototype? or a list of functions that need to be converted? 
> 
> Currently, I'm working on the following functions: 
> ```
> __declspec(dllimport) bool HyperDbgCheckMultilineCommand(std::string & CurrentCommand, bool Reset);
> __declspec(dllimport) void HyperDbgScriptReadFileAndExecuteCommand(std::vectorstd::string & PathAndArgs);
> ```
> 
> Is there anything else?
> 

Yeah, if the sdk import the debugger ctx'api , we can bind them to go without stl type, now we have two way call debug ctx : script command and sdk api.

**Comment by ddkwork** [comment]
> Okay, the function you mentioned are now converted to C types : 
> 
> https://github.com/HyperDbg/HyperDbg/commit/1b9ba13d5d13aa84faeba9b9f2e39cdc3aff9258

I will try. Cool for you.

**Comment by ddkwork** [comment]
> Please let me know if anything else needs to be changed.
> 

Okay
