### ISSUE TITLE
Performance problems of ui

### ISSUE THREAD

**Issue by ddkwork** [HyperDbg/gui#17]

**Comment by ddkwork** [comment]
During this time, I used the gui of go language to implement a package capture program, and the gui of hyperdng used the form control. I found that the form has no problem for loading complete data at one time, but the performance of dynamically adding rows is not good. At present, I am studying another gui scheme using Google skia, but I am still learning how to use it, so I can't replace the current ui interface for the time being.

**Comment by ddkwork** [comment]
If you are also a lover of go language, please submit a pr after you pass the unit test. Of course, if I master this technology first, I will give priority to the gui v2 version. During this period, dll and c api will be bound to go language, and a lot of binding codes need to be written. If you are interested, please submit pr to speed up the connection between gui and hyperdbg driver layer. The expected goal is to be as easy to use as x64dbg.

**Comment by ddkwork** [comment]
Newer ui lib choose:

https://github.com/richardwilkes/unison

**Comment by SinaKarvandi** [comment]
Well, that's great. Yes, I might not be good at GO but I will try to learn it.

` > During this period, dll and c api will be bound to go language, and a lot of binding codes need to be written. 
`
Please tell me the specific tasks like converting these APIs from xxx to yyy, so I can convert them for you. Or if there are any other modifications that need to be done on C or C++ project at this time, please let me know.

**Comment by ddkwork** [comment]
> Well, that's great. Yes, I might not be good at GO but I will try to learn it.
> 
> ` > During this period, dll and c api will be bound to go language, and a lot of binding codes need to be written. 
> `
> Please tell me the specific tasks like converting these APIs from xxx to yyy, so I can convert them for you. Or if there are any other modifications that need to be done on C or C++ project at this time, please let me know.

Okay

**Comment by ddkwork** [comment]
hi, if you have free time, please help layout the table widget.

![image](https://user-images.githubusercontent.com/19886504/204965350-1bb6dc83-066e-41a9-98c1-68ada1c9f412.png)

demo rep:
https://github.com/ddkwork/unisonUi

**Comment by SinaKarvandi** [comment]
Hi,
Currently, I'm finishing the refactoring codes of HyperDbg at : https://github.com/HyperDbg/HyperDbg/tree/refactor-vcpu 

I'll join you later.

**Comment by ddkwork** [comment]
> Hi,
> Currently, I'm finishing the refactoring codes of HyperDbg at : https://github.com/HyperDbg/HyperDbg/tree/refactor-vcpu 
> 
> I'll join you later.

nice， and if you have vps，please give me one，i use it connect ssh etc for open Google，github， China's vpn so bad.

**Comment by ddkwork** [comment]
As for go language, I think the fastest way for us to communicate is this: run jetb goland ide on your machine, then open code with me, then you send me the token, and I will connect to your computer. At this time, we are coding, compiling, testing and discussing on the same screen, which is very real-time.

**Comment by ddkwork** [comment]
> > Hi,
> > Currently, I'm finishing the refactoring codes of HyperDbg at : https://github.com/HyperDbg/HyperDbg/tree/refactor-vcpu 
> > 
> > I'll join you later.
> 
> nice， and if you have vps，please give me one，i use it connect ssh etc for open Google，github， China's vpn so bad.

![Screenshot_20221202_131844_org.telegram.messenger.web.jpg](https://user-images.githubusercontent.com/19886504/205220317-fda119e1-69ec-41ae-b439-ee2cb53646c6.jpg)

need vpn

**Comment by ddkwork** [comment]
https://www.jetbrains.com/code-with-me/

**Comment by SinaKarvandi** [comment]
I have some VMESS VPNs. I can send it to you. Would you please give me your email address so I can privately send the credentials to you?

**Comment by ddkwork** [comment]
> I have some VMESS VPNs. I can send it to you. Would you please give me your email address so I can privately send the credentials to you?

2762713521@qq.com

Thx you.

**Comment by ddkwork** [comment]
I'm a little curious that your country also needs vpn. As far as I know, except China, you can't access Google, so it seems that other countries can. What's worse: in China, it's not just the problem of not being able to access Google. After accessing github, it can't be accessed for tens of seconds or even half an hour, and then it resumes for about a minute. It's intermittent and quite a bad network.

**Comment by ddkwork** [comment]
good

![image](https://user-images.githubusercontent.com/19886504/205311367-9c877a88-d974-4aea-b4ea-d98fbe3f4161.png)

**Comment by ddkwork** [comment]
I encountered another layout problem: the layout of the two controls, tab and table, is not normal. If the table layout is set to flex, the table contents will not be displayed. If the table layout is not specified, the table data will be displayed, but the video card is arranged at the bottom, and the tab layout is invisible.

**Comment by ddkwork** [comment]
I encountered another layout problem: the layout of two controls, tab and table, is not normal. If the table layout is set to flex, the table contents will not be displayed. If the table layout is not specified, the table data will be displayed, but the tabs are arranged at the bottom, so the tab layout can't be seen.

**Comment by ddkwork** [comment]
![image](https://user-images.githubusercontent.com/19886504/205436700-0e6e0139-84dd-4db4-82bc-3846d012508a.png)

v2 starting, please join me codeing
