### ISSUE TITLE
Enum debugee

### ISSUE THREAD

**Issue by ddkwork** [HyperDbg/gui#18]
hello you， can i add a type for debugee status？

the ide show the iota value is not right

![Screenshot_20221118_105028_com.realvnc.viewer.android.jpg](https://user-images.githubusercontent.com/19886504/202606163-3eea9d34-3c39-4909-9e3f-61b49ef13394.jpg)

**Comment by SinaKarvandi** [comment]
yes, sure. Apply it to the "dev" branch of the main repo.
