### ISSUE TITLE
fatal: repository 'https://github.com/ddkwork/app/' not found

### ISSUE THREAD

**Issue by piaoyunsoft** [HyperDbg/gui#181]
fatal: repository 'https://github.com/ddkwork/app/' not found

**Comment by fire988** [comment]
the same issue

**Comment by ClothingAI** [comment]
same but for 
**fatal: repository 'https://github.com/kohya-ss/sd-script/' not found**

**Comment by ClothingAI** [comment]
I just forgot a letter at the end.

**Comment by ddkwork** [comment]
Let me check it.
