### ISSUE TITLE
api changed?

### ISSUE THREAD

**Issue by ddkwork** [HyperDbg/gui#186]
Hi, SinaKarvandi. 我今天升级了sdk，发现有个api似乎更改了名称，名称改成什么了？

https://github.com/ddkwork/gui/blob/main/sdk%2Futil.go#L69-L70

WhatsApp收不到短信验证码了，只能在这交流了。

**Comment by SinaKarvandi** [comment]
Yes it's changed to `hyperdbg_u_run_command`.

**Comment by ddkwork** [comment]
> Yes it's changed to `hyperdbg_u_run_command`.

okay
