### ISSUE TITLE
callback fn need define a name

### ISSUE THREAD

**Issue by ddkwork** [HyperDbg/gui#19]
* as a custom ShowMessages function
 *
 */
typedef int (*Callback)(const char * Text);

//////////////////////////////////////////////////
//

![Screenshot_20221118_111930_com.realvnc.viewer.android.jpg](https://user-images.githubusercontent.com/19886504/202609213-1e1856f0-c6ce-49fb-ad81-efdee2fc2aa9.jpg)

hello you , the method type define need give it a name in golang.

**Comment by SinaKarvandi** [comment]
What do you mean? I didn't get the point.

**Comment by ddkwork** [comment]
> What do you mean? I didn't get the point.

wait，i am not sure

**Comment by ddkwork** [comment]
> What do you mean? I didn't get the point.

hi，are you have free time，please continue bind this file and other 2 file，the bind work will finished。

https://github.com/ddkwork/gui/blob/main/SDK/Headers/RequestStructures.h.go

**Comment by ddkwork** [comment]
fix all todo marked
