### ISSUE TITLE
There is no way to inject ghidra's decompiler.

### ISSUE THREAD

**Issue by ddkwork** [HyperDbg/gui#23]

**Comment by SinaKarvandi** [comment]
Hi,
What do you mean by "Ghidra's decompiler"? do you want to integrate HyperDbg and Ghidra?

Thanks,

**Comment by ddkwork** [comment]
> Hi,
> What do you mean by "Ghidra's decompiler"? do you want to integrate HyperDbg and Ghidra?
> 
> Thanks,

Yes,  ghidra f5 very nice.

**Comment by SinaKarvandi** [comment]
Hi,
Yes, it's very nice. Personally, I love using IDA's decompiler however, both of them are okay. Personally, I think it's better to integrate them in a plugin-style format but if you think we should add it directly to the project, that's okay. I'll put it on the to-do list for future releases.

Thanks.

**Comment by ddkwork** [comment]
No matter which decompiler you choose to integrate, I'm all for it. However, I've heard that decompilers are strongly dependent on disassembly engines. As far as ghidra is concerned, otherwise, we will encounter many problems when we load buffer into engines. Therefore, it's not known how the integration of zydis and ghidra's disassembly engines is, and ida hasn't studied it because it avoids sources. Plug-ins are fine. Implanting the main project may be too complicated. Plug-ins should have less impact.

**Comment by ddkwork** [comment]
So it is still necessary to export the dll interface to facilitate the operation on the gui to select which address to output pseudo code. For example, the unit price is 0x4012000. Call the api for reading memory to the dll, return the buffer and load it into the decoder engine. . . It doesn't seem quite right either, because this thing needs to decode all types to match the pseudo-code type check, so it needs to load all buffer, or should it be integrated into the dll main module? I'm not sure, but this function is really good. By then, we can not only output the pseudo-code of C language, but also the pseudo-code of go. Wonderful.

**Comment by ddkwork** [comment]
> Well, I think they have support to send the bytes (instead of Zydis disassembled codes) and they'll do the same. We need to investigate it as a planned feature. I'll add it to my to-do list.

There is no way for it to generate dll,. lib, .a, which supports building from source code, so it can be compiled directly by cgo. dll binding can only be used on Windows, and it is not universal. Source code compilation with cgo can be used with CPUs of various platforms and architectures such as linux and Windows.

https://github.com/NationalSecurityAgency/ghidra/tree/master/Ghidra%2FFeatures%2FDecompiler%2Fsrc%2Fdecompile%2Fcpp

**Comment by ddkwork** [comment]
Finally, let's use zydis or other disassembly engines to reconstruct the data structure required by the decompiler, and fill the buffer returned after reading from the driver into the structure of our modified disassembly engine. If we are lucky, we will get C language pseudo-code and go language pseudo-code. Finally, we make this function work in all environments such as Android, pc, tablet, virtual machine, etc. It's awesome. This function.

**Comment by SinaKarvandi** [comment]
Hi,

I'm not sure if I understand what you mean. Do you mean that we should borrow C (CPP) codes of the Ghirdra decompiler and compile them directly into our hprdbgctrl?

**Comment by ddkwork** [comment]
> Hi,\n\nI'm not sure if I understand what you mean. Do you mean that we should borrow C (CPP) codes of the Ghirdra decompiler and compile them directly into our hprdbgctrl?

yes

**Comment by SinaKarvandi** [comment]
By the way, it's really hard to maintain such code. I saw Ghirdra's license. It allows us to use it; however, they change their code base frequently. Like fixing the bugs, adding new features, and enhancing the decompiler. So, we always have to look at their base code for possible improvement, and it's really a mess.
