### ISSUE TITLE
Select a data storage method for the debugger.

### ISSUE THREAD

**Issue by ddkwork** [HyperDbg/gui#24]
Redis ？

**Comment by SinaKarvandi** [comment]
Hi,
I don't have any idea about "redis", but I can read about it. What kind of data do we need to store for the debugger?

Thanks

**Comment by ddkwork** [comment]
> Hi,\nI don't have any idea about \"redis\", but I can read about it. What kind of data do we need to store for the debugger?\n\nThanks

I think some work about debug need save, break list, comment etc.

**Comment by SinaKarvandi** [comment]
Is it too complex to be handled by a simple file? Isn't it possible to use regular file saving?

**Comment by ddkwork** [comment]
> Is it too complex to be handled by a simple file? Isn't it possible to use regular file saving?

Sure, but you should choose a type that is easy to import into the table, such as json. If the field type is binary, you should choose database.

**Comment by SinaKarvandi** [comment]
Hi,
Agree. But just to make sure, did you see the INI codes used in hprdbgctrl interface for binding?

Here is an example of where we used it : 
https://github.com/HyperDbg/HyperDbg/blob/1b9ba13d5d13aa84faeba9b9f2e39cdc3aff9258/hyperdbg/hprdbgctrl/code/debugger/commands/debugging-commands/settings.cpp#L91

Isn't it okay for our case? Do we still need a better and more complex (with more features) data storage management?

**Comment by ddkwork** [comment]
> Hi,
> Agree. But just to make sure, did you see the INI codes used in hprdbgctrl interface for binding?
> 
> Here is an example of where we used it : 
> https://github.com/HyperDbg/HyperDbg/blob/1b9ba13d5d13aa84faeba9b9f2e39cdc3aff9258/hyperdbg/hprdbgctrl/code/debugger/commands/debugging-commands/settings.cpp#L91
> 
> Isn't it okay for our case? Do we still need a better and more complex (with more features) data storage management?

Oh, I haven't read the implementation process of this code carefully. So can ini be bound to structural objects? For example, struct {}, after specifying some fields for it, can it be directly filled into the structure through the encoding and decoding of ini? Why do you need this feature? Because the configuration needs to be loaded into the list item of the gui table in the easiest way, if it can't be loaded from the structure, then every row of the gui table needs cumbersome data control methods of each row and column, which becomes cumbersome. If structure loading is supported, then the data merging method with gui becomes: read the structure slice, which can also be called the structure array. A structure is a row of data in the table, and we can refresh all the data to gui only by traversing the structure. If you have a better idea, please let me know. Thank you.

**Comment by SinaKarvandi** [comment]
> or example, struct {}, after specifying some fields for it, can it be directly filled into the structure through the encoding and decoding of ini? Why do you need this feature? Because the configuration needs to be loaded into the list item of the gui table in the easiest way, if it can't be loaded from the structure, then every row of the gui table needs cumbersome data control methods of each row and column, which becomes cumbersome. If structure loading is supported, then the data merging method with gui becomes: read the structure slice, which can also be called the structure array. A structure is a row of data in the table, and we can refresh all the data to gui only by traversing the structure. If you have a better idea, please let me know. Thank you

Yeah, agree. We should add such a feature in HyperDbg. I will add it to my to-do list. By the way, we should find a solution that is easy to extend and compatible with other platforms (like Linux) because, in the development roadmap, we want to reach basic support for the Linux systems too.
