### ISSUE TITLE
Symbol buffer define

### ISSUE THREAD

**Issue by ddkwork** [HyperDbg/gui#25]
hello you，What's these define？i can not use Windows now

![Screenshot_20221119_103828_com.realvnc.viewer.android.jpg](https://user-images.githubusercontent.com/19886504/202830493-ad6532dc-4770-4f92-b292-bbd21f44db3d.jpg)

**Comment by SinaKarvandi** [comment]
Hi,
These are the script engine's definitions. We now use these definitions in both user mode and kernel-mode as these definitions in the script engine are used in these two execution modes.

**Comment by ddkwork** [comment]
> Hi,
> These are the script engine's definitions. We now use these definitions in both user mode and kernel-mode as these definitions in the script engine are used in these two execution modes.

Ok, i will search them

**Comment by ddkwork** [comment]
founded
