### ISSUE TITLE
init dll

### ISSUE THREAD

**Issue by ddkwork** [HyperDbg/gui#28]
todo test on windows

**Comment by ddkwork** [comment]
Hello, all the binding work has been completed, but I can't use Windows test loading for the time being. When you are free, clone it and test it. Enter the source directory and execute the command Go Mod Tidy. The main function will perform the loading dll function. In addition, you need to copy the driver to the dll directory to load the dll driver.

**Comment by ddkwork** [comment]
Need remove go.work

**Comment by ddkwork** [comment]
Please help me merge all comment and remove all cache, i found the git rep is more than more biger.

**Comment by ddkwork** [comment]
All C language binding to go language has been completed, but I can't use the computer recently and can't test it on Windows.

**Comment by ddkwork** [comment]
> Hi,\nThat's great. I'll test it.\nOne question, is it automatically binds the C language to GO? For example by running a script? or should we manually add (and change) the new structures to the GO language?\n\nThanks

At present, it is automatic, not fully automatic conversion and generation of binding code. Remember how long ago I tried to translate C code in batches? At that time, I ignored these questions I asked you these days. Through the process of manual code conversion during this time, I learned that 30% of C codes can read your sdk to automatically generate go codes. However, there are some differences between the language features of C and go languages. I think there will still be problems with automatic batch conversion. If you write conversion codes for each C file separately, there will be no problems. For example, in C language, enum, the corresponding business code may be an integer list with increasing values, so its increasing type is byte, uint and so on. However, through manual translation, I found that enum may also be func, a function type, such as io ctrol code. C language uses macros to express the implementation process of enum, while go language does not have the language features of macros. At this time, I can only say that io control codes are realized by functions, so enum is realized by integers. There are many similar situations, which indirectly leads to poor compatibility of automated translation codes. However, instead of letting go translate C language, it's better to let hydbg directly generate the binding code, because at present, we have mastered what kind of go language code needs to be output in every detail of sdk, so it will be relatively easy to output the binding code in dll layer and easy to control in implementation. Please correct me if my train of thought is wrong. Thank you.

**Comment by ddkwork** [comment]
By the way, can nested folders in sdk folders be merged into one folder? If package management is used to discuss it, they should be divided into the same package.

**Comment by SinaKarvandi** [comment]
> C language uses macros to express the implementation process of enum, while go language does not have the language features of macros. At this time, I can only say that io control codes are realized by functions, so enum is realized by integers. There are many similar situations, which indirectly leads to poor compatibility of automated translation codes. However, instead of letting go translate C language, it's better to let hydbg directly generate the binding code, because at present, we have mastered what kind of go language code needs to be output in every detail of sdk, so it will be relatively easy to output the binding code in dll layer and easy to control in implementation. Please correct me if my train of thought is wrong. Thank you.

Hi,
Sorry for the delayed reply. 

Yes, I understand what you mean. Maybe we can join the translator code from C to GO to the main repository of the project. If you think it's better, we can do it. For example, after compiling, we can easily create the GO codes for the SDK. What do you think about it?

**Comment by SinaKarvandi** [comment]
> By the way, can nested folders in sdk folders be merged into one folder? If package management is used to discuss it, they should be divided into the same package.

Do you mean that all header files should be in the same folder?

**Comment by ddkwork** [comment]
> > C language uses macros to express the implementation process of enum, while go language does not have the language features of macros. At this time, I can only say that io control codes are realized by functions, so enum is realized by integers. There are many similar situations, which indirectly leads to poor compatibility of automated translation codes. However, instead of letting go translate C language, it's better to let hydbg directly generate the binding code, because at present, we have mastered what kind of go language code needs to be output in every detail of sdk, so it will be relatively easy to output the binding code in dll layer and easy to control in implementation. Please correct me if my train of thought is wrong. Thank you.
> 
> Hi,
> Sorry for the delayed reply. 
> 
> Yes, I understand what you mean. Maybe we can join the translator code from C to GO to the main repository of the project. If you think it's better, we can do it. For example, after compiling, we can easily create the GO codes for the SDK. What do you think about it?

I propose to suspend this. I will decide whether to do it or not after I pass the dynamic loading performance test of the new ui framework. I am preparing to write the unit test of the new framework.

**Comment by ddkwork** [comment]
> > By the way, can nested folders in sdk folders be merged into one folder? If package management is used to discuss it, they should be divided into the same package.
> 
> Do you mean that all header files should be in the same folder?

From the syntax of go language, all folders in sdk folder are in the same layer of business, so the coupling is high. Unpacking will increase the complexity. For example, the imports package refers to the basic data type definition of headers package, and the readability will become bad when more features are added in the future. However, don't change it for the time being. We'll discuss how to optimize readability when I test the new ui framework and ensure stable ui performance.
