### ISSUE TITLE
BUFFER_HEADER

### ISSUE THREAD

**Issue by ddkwork** [HyperDbg/gui#33]
Hi, Where can find BUFFER_HEADER define ?

![Screenshot_20221121_014455_com.realvnc.viewer.android.jpg](https://user-images.githubusercontent.com/19886504/202917586-e26a8823-ab5e-430c-9785-99f8f9e773f2.jpg)

**Comment by SinaKarvandi** [comment]
Hi, 

The BUFFER_HEADER is an internal structure defined for storing messages and general buffers in kernel mode and sending them back to the user mode.

Please take a look at "Designing A VMX Root-mode Compatible Message Tracing" at https://rayanfam.com/topics/hypervisor-from-scratch-part-8/ for more information about how this buffer works.

Generally, I think there is no need to use this structure if you're using APIs, everything is handled in the driver and user-mode interface (Interface DLL).


![image](https://user-images.githubusercontent.com/13383992/202949221-845c13d7-f7af-4e9b-91c9-bee8d5782349.png)

**Comment by ddkwork** [comment]
Ok
