### ISSUE TITLE
Api name too long

### ISSUE THREAD

**Issue by ddkwork** [HyperDbg/gui#34]

**Comment by ddkwork** [comment]
maybe we can use namespace.

**Comment by SinaKarvandi** [comment]
Hi,
Unfortunately, there is no namespace in C language, and as the driver is entirely written in C, there is no way to use a namespace in SDK. But if that's problematic in GO, please tell me the tool-long API names, so I will make them smaller.

Thanks

**Comment by ddkwork** [comment]
> Hi,
> Unfortunately, there is no namespace in C language, and as the driver is entirely written in C, there is no way to use a namespace in SDK. But if that's problematic in GO, please tell me the tool-long API names, so I will make them smaller.
> 
> Thanks

![Screenshot_20221121_112914_com.realvnc.viewer.android.jpg](https://user-images.githubusercontent.com/19886504/202959622-f94f4cb6-79f3-4c5f-a6e9-03d5aa712582.jpg)

rename them, 2 api, let all symbol methods have same sign.

**Comment by ddkwork** [comment]
![Screenshot_20221121_113551_com.realvnc.viewer.android.jpg](https://user-images.githubusercontent.com/19886504/202960402-04465d87-1230-4be3-b9fd-287144c039b9.jpg)

Remove this line, it is repeated.
