### ISSUE TITLE
对于cli，需要更多的驱动通信控制权

### ISSUE THREAD

**Issue by ddkwork** [HyperDbg/gui#57]
在我用go代码读取ntoskenl解析pe并找到ssdt，iopxxxcontrolfile等等这些操作的过程中，就算目的再怎么复杂，只要驱动返回给gui需要的内存数据，go代码都能很容易实现，这像写js脚本一样简单。但这些过程要是用heyoerdbg脚本或者cpp sdk api的形式去操作，n多bsod和繁杂的代码等着你。

ollydbg和x64dbg写脚本也是糟糕的体验

所以，使用go代码来编写脚本过程成了我的最终目标。

而hyperdbg的sdk似乎没有提供更多的权限，需要进一步调查

**Comment by SinaKarvandi** [comment]
> 而hyperdbg的sdk似乎没有提供更多的权限，需要进一步调查

What kind of modification do you need on SDK? Please let me know so I can implement your needed functionalities.

您需要对 SDK 进行哪些修改？请告知我，以便我实现您所需的功能。

**Comment by ddkwork** [comment]
稍等，等我准备好各种测试交互的时候我再请教您



---原始邮件---
发件人: "Sina ***@***.***&gt;
发送时间: 2024年6月14日(周五) 中午12:02
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [HyperDbg/gui] 对于cli，需要更多的驱动通信控制权 (Issue #57)




  
而hyperdbg的sdk似乎没有提供更多的权限，需要进一步调查
  
What kind of modification do you need on SDK? Please let me know so I can implement your needed functionalities.
 
您需要对 SDK 进行哪些修改？请告知我，以便我实现您所需的功能。

**Comment by ddkwork** [comment]
调试器的控制库似乎级联依赖dll
